apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/payment_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
